version: 2.1
orbs:
  cloudrun: circleci/gcp-cloud-run@1.0.0
  gcp-gcr: circleci/gcp-gcr@0.6.1
jobs:
  build_push_image_cloud_run_managed:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false
      - run:
          name: Build docker image
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            echo ${GCP_PROJECT_KEY} | base64 --decode --ignore-garbage > $HOME/gcloud-service-key.json
            echo 'export GOOGLE_CLOUD_KEYS=$(cat $HOME/gcloud-service-key.json)' >> $BASH_ENV
            echo 'export TAG=${CIRCLE_SHA1}' >> $BASH_ENV
            echo 'export IMAGE_NAME=$CIRCLE_PROJECT_REPONAME' >> $BASH_ENV && source $BASH_ENV
            docker build --build-arg FIREBASE_CONFIG_B64=${FIREBASE_CONFIG_B64} --build-arg FIREBASE_FIRESTORE_ID=${FIREBASE_FIRESTORE_ID} -t gcr.io/$GOOGLE_PROJECT_ID/$IMAGE_NAME -t gcr.io/$GOOGLE_PROJECT_ID/$IMAGE_NAME:$TAG .
      - gcp-gcr/gcr-auth:
          gcloud-service-key: GOOGLE_CLOUD_KEYS
          google-project-id: GOOGLE_PROJECT_ID
          google-compute-zone: GOOGLE_COMPUTE_ZONE
      - gcp-gcr/push-image:
          google-project-id: GOOGLE_PROJECT_ID
          registry-url: "gcr.io"
          image: $IMAGE_NAME
      - cloudrun/deploy:
          platform: "managed"
          image: "gcr.io/$GOOGLE_PROJECT_ID/$IMAGE_NAME"
          service-name: "keepclone"
          region: $GOOGLE_COMPUTE_ZONE
          unauthenticated: true
workflows:
  build_deploy:
    jobs:
      - build_push_image_cloud_run_managed:
          filters:
            branches:
              only:
                - master