export const AUTH_LOADING_STATE = 'auth/AUTH_LOADING_STATE';

export const LOGIN_SUCCESS = 'auth/AUTH_LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'auth/AUTH_LOGOUT_SUCCESS';

export const CHANGE_COLOR_MODE = 'app/CHANGE_COLOR_MODE';

export const REORDER_LOCAL_NOTES = 'app/REORDER_LOCAL_NOTES';
export const SAVE_LOCAL_NOTE = 'app/SAVE_LOCAL_NOTE';

export const SAVE_LOCAL_LABEL = 'app/SAVE_LOCAL_LABEL';
export const UPDATE_LOCAL_LABEL = 'app/UPDATE_LOCAL_LABEL';
export const BULK_UPDATE_LOCAL_LABELS = 'app/BULK_UPDATE_LOCAL_LABELS';
export const DELETE_LOCAL_LABEL = 'app/DELETE_LOCAL_LABEL';
