export const AUTH_LOADING_STATE = 'auth/AUTH_LOADING_STATE';

export const LOGIN_SUCCESS = 'auth/AUTH_LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'auth/AUTH_LOGOUT_SUCCESS';

export const CHANGE_COLOR_MODE = 'app/CHANGE_COLOR_MODE';

export const REORDER_LOCAL_NOTES = 'app/REORDER_LOCAL_NOTES';
export const SAVE_LOCAL_NOTE = 'app/SAVE_LOCAL_NOTE';

export const SAVE_LOCAL_LABEL = 'app/SAVE_LOCAL_LABEL';
export const UPDATE_LOCAL_LABEL = 'app/UPDATE_LOCAL_LABEL';
export const BULK_UPDATE_LOCAL_LABELS = 'app/BULK_UPDATE_LOCAL_LABELS';
export const DELETE_LOCAL_LABEL = 'app/DELETE_LOCAL_LABEL';

export const SET_SELECTED_LABEL = 'app/SET_SELECTED_LABEL';

export const DELETE_LOCAL_NOTE = 'app/DELETE_LOCAL_NOTE';
export const RESTORE_LOCAL_NOTE = 'app/RESTORE_LOCAL_NOTE';
export const PERMANETLY_DELETE_LOCAL_NOTE = 'app/PERMANENTLY_DELETE_LOCAL_NOTE';

export const ARCHIVE_LOCAL_NOTE = 'app/ARCHIVE_LOCAL_NOTE';
export const UNARCHIVE_LOCAL_NOTE = 'app/UNARCHIVE_LOCAL_NOTE';

export const CHANGE_LOCAL_NOTE_BACKGROUND = 'app/CHANGE_LOCAL_NOTE_BACKGROUND';

export const TOGGLE_LOCAL_NOTE_LABEL = 'app/TOGGLE_LOCAL_NOTE_LABEL';

export const UPDATE_FIREBASE_NOTES = 'app/UPDATE_FIREBASE_NOTES';
export const UPDATE_FIREBASE_LABELS = 'app/UPDATE_FIREBASE_LABELS';

export const SET_SELECTED_NOTE = 'app/SET_SELECTED_NOTE';

export const SET_TOAST_PROPS = 'app/SET_TOAST_PROPS';
export const CLOSE_TOAST = 'app/CLOSE_TOAST';
